Added French translation
jptrrs/HumanResources pull request #74
Opened 2020-08-20 19:30 UTC by Arsaell

This is a first shot at a french translation for this mod.

I haven't spent a long time testing the mod in-game, so for some of the strings I had to guess in what context they would be used, and i have probably been wrong some (many ?) times. The base meaning should be there anyways, it just the word endings that might be funny.

Plus, it is my first contribution to any rimworld mod, so i haven't the slightest idea if I'm supposed to write anything elsewhere than in this languages folder ? There might be a list of supported languages somewhere, which should then be updated ?

Kuddos !

2020-09-18 21:36 UTC, jptrrs commented
Génial, Remi! Merci beaucoup!
I was forced to take a break from modding last month, and only now I'm
taking some time to update my mods. But I'm thrilled to add a french
version! You're very much welcome to the team.
I'll look into your translation asap, but I'm probably going to ask you to
add some lines before I can integrate this. That's because I made some
improvements right before Tynan updated RW, and I haven't published them
yet. Are you still up for a quick revision?

João Pedro


On Thu, Aug 20, 2020 at 4:30 PM Rémi Dupouy <notifications@github.com>
wrote:

> This is a first shot at a french translation for this mod.
>
> I haven't spent a long time testing the mod in-game, so for some of the
> strings I had to guess in what context they would be used, and i have
> probably been wrong some (many ?) times. The base meaning should be there
> anyways, it just the word endings that might be funny.
>
> Plus, it is my first contribution to any rimworld mod, so i haven't the
> slightest idea if I'm supposed to write anything elsewhere than in this
> languages folder ? There might be a list of supported languages somewhere,
> which should then be updated ?
>
> Kuddos !
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/jptrrs/HumanResources/pull/74
> Commit Summary
>
>    - Added French translation
>
> File Changes
>
>    - *A* Languages/French/DefInjected/JobDef/Jobs.xml
>    <https://github.com/jptrrs/HumanResources/pull/74/files#diff-70c2510d30f4a14bf4e372b7ad66eb1b>
>    (14)
>    - *A* Languages/French/DefInjected/RecipeDef/Recipes.xml
>    <https://github.com/jptrrs/HumanResources/pull/74/files#diff-b32930837b43aa9f7c717cdad9795879>
>    (58)
>    - *A* Languages/French/DefInjected/RoomRoleDef/Rooms.xml
>    <https://github.com/jptrrs/HumanResources/pull/74/files#diff-7305b215078fa51d6c3798eaa73794ed>
>    (8)
>    - *A* Languages/French/DefInjected/ScenPartDef/ScenParts.xml
>    <https://github.com/jptrrs/HumanResources/pull/74/files#diff-5d46188c1f0adcf175d1278cc7f49181>
>    (10)
>    - *A* Languages/French/DefInjected/StuffCategoryDef/StuffCategories.xml
>    <https://github.com/jptrrs/HumanResources/pull/74/files#diff-4b40a06dc1936a250eada66c2286fd64>
>    (8)
>    - *A* Languages/French/DefInjected/ThingCategoryDef/ThingCategories.xml
>    <https://github.com/jptrrs/HumanResources/pull/74/files#diff-5eb3445b43004b4c2eb6ddfd2234ae28>
>    (20)
>    - *A* Languages/French/DefInjected/ThingDef/Things.xml
>    <https://github.com/jptrrs/HumanResources/pull/74/files#diff-00d33e7c774840b5dddfab5775903106>
>    (42)
>    - *A* Languages/French/DefInjected/ThingDef/Things_WeaponsNotBasic.xml
>    <https://github.com/jptrrs/HumanResources/pull/74/files#diff-79cb55792abcb942799aa11174c666c0>
>    (9)
>    - *A* Languages/French/DefInjected/TraderKindDef/TraderKinds.xml
>    <https://github.com/jptrrs/HumanResources/pull/74/files#diff-0f39514a6bc49c55e719cdf4f79630ff>
>    (10)
>    - *A* Languages/French/DefInjected/WorkGiverDef/WorkGivers.xml
>    <https://github.com/jptrrs/HumanResources/pull/74/files#diff-a72af967a069483b0d501fb6dfc87d7b>
>    (40)
>    - *A* Languages/French/DefInjected/WorkTypeDef/WorkTypes.xml
>    <https://github.com/jptrrs/HumanResources/pull/74/files#diff-6921834179344ccb9d69d2bc18fa7b4a>
>    (17)
>    - *A* Languages/French/Keyed/HumanResources_keys.xml
>    <https://github.com/jptrrs/HumanResources/pull/74/files#diff-5b4bc014bdc3f6b88eb6d937dcf54f1b>
>    (147)
>
> Patch Links:
>
>    - https://github.com/jptrrs/HumanResources/pull/74.patch
>    - https://github.com/jptrrs/HumanResources/pull/74.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jptrrs/HumanResources/pull/74>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALHBNPX5F6Z5QRN22XFGFO3SBV2XFANCNFSM4QGQSRMA>
> .
>

2020-10-04 23:11 UTC, jptrrs requested changes
Hi there, Rémi!
I reviewed your translations and it seems just fine. I left a note, but the only major thing we would need to add would be the new lines for our next update. I added them to your keys file and explained it there. 
Hope you're still up to the task!

2020-10-04 23:11 UTC, jptrrs commented on Languages/French/DefInjected/JobDef/Jobs.xml
> +  <TrainWeapon.reportString>S'entraîne avec TargetB.</TrainWeapon.reportString>
We lost the "Target B" on these lines to leave just the verb.

2020-10-06 10:50 UTC, Arsaell commented
Hi there !

I just applied the changes you requested, it should be ok for now...
Don't hesitate to come to me if there are other updates you need translated !

Keep it going, and have a nice one !
PN.

2020-10-06 15:28 UTC, jptrrs approved these changes
Great! On parle français maintenant! Merci.

2020-10-06 15:29 UTC, merged

2020-12-01 15:51 UTC, jptrrs commented
Hey, Rémi!
I'm writing here because I really have no other means of contacting you. 
Since your translation, we have added a bunch of new lines to the mod. It would be nice if you could update it! The changes were mostly on [the main keys file](https://github.com/jptrrs/HumanResources/blob/master/Languages/French/Keyed/HumanResources_keys.xml) and on the [Jobs file](https://github.com/jptrrs/HumanResources/blob/master/Languages/French/DefInjected/JobDef/Jobs.xml). I've marked them all with `<!--NEW-->`.
Thank you very much!